CREATE DATABASE IF NOT EXISTS BUDU;
USE BUDU;

CREATE TABLE users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE email_messages (
    id INT AUTO_INCREMENT PRIMARY KEY,
    username TEXT DEFAULT('anonim'),
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP
);

SELECT * FROM budu.email_messages;
SELECT * FROM budu.users;

DROP TABLE email_messages;
DROP DATABASE BUDU;